# zeabur.yaml
version: v1
name: n8n

services:
  n8n:
    provider: docker
    build: .           # 使用上面这个 Dockerfile 来构建镜像
    ports:
      - "5678:5678"

    # 以下 env 全量保留，值使用 Zeabur 控制台中设置的环境变量
    env:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: ${POSTGRES_HOST}
      DB_POSTGRESDB_PORT: ${POSTGRES_PORT}
      DB_POSTGRESDB_DATABASE: ${POSTGRES_DATABASE}
      DB_POSTGRESDB_USER: ${POSTGRES_USERNAME}
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}

      N8N_HOST: ${ZEABUR_WEB_DOMAIN}
      WEBHOOK_URL: ${ZEABUR_WEB_URL}

      GENERIC_TIMEZONE: Asia/Taipei
      NODE_ENV: production

      N8N_RUNNERS_ENABLED: "true"
      N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE: "true"
      N8N_DIAGNOSTICS_ENABLED: "false"

      N8N_ENCRYPTION_KEY: ${PASSWORD}
      PUBLIC_DOMAIN: xxt