version: v1
name: n8n

services:
  n8n:
    provider: docker
    build: .
    ports:
      - "5678:5678"
    volumes:
      - name: downloads
        mountPath: /home/node/downloads
      - name: fonts
        mountPath: /home/node/.n8n/fonts
    env:
      - name: DB_TYPE
        value: postgresdb
      - name: DB_POSTGRESDB_HOST
        value: ${POSTGRES_HOST}
      - name: DB_POSTGRESDB_PORT
        value: ${POSTGRES_PORT}
      - name: DB_POSTGRESDB_DATABASE
        value: ${POSTGRES_DATABASE}
      - name: DB_POSTGRESDB_USER
        value: ${POSTGRES_USERNAME}
      - name: DB_POSTGRESDB_PASSWORD
        value: ${POSTGRES_PASSWORD}
      - name: N8N_HOST
        value: ${ZEABUR_WEB_DOMAIN}
      - name: WEBHOOK_URL
        value: ${ZEABUR_WEB_URL}
      - name: GENERIC_TIMEZONE
        value: Asia/Taipei
      - name: NODE_ENV
        value: production
      - name: N8N_RUNNERS_ENABLED
        value: "true"
      - name: N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE
        value: "true"
      - name: N8N_DIAGNOSTICS_ENABLED
        value: "false"
      - name: N8N_ENCRYPTION_KEY
        value: ${PASSWORD}
      - name: PUBLIC_DOMAIN
        value: xxt